### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by hickscorp** [smcameron/open-simplex-noise-in-c#6]
Hello,

I have made a small wrapper around your work, and would like to know if it's okay for me to put it on github: hickscorp/osimplex

Thanks.

**Comment by smcameron** [comment]
Of course it's fine.  I put it in the public domain explicitly (see https://github.com/smcameron/open-simplex-noise-in-c/blob/master/LICENSE ) because the code it is based on was also in the public domain, so that seemed the respectful thing to do, and I can't really claim to be the "author" of this code, more like the "translator" -- I just translated some java code into C.   So far as I know, It is not a requirement that you put your derivative work into the public domain -- since it is public domain, you can do anything you like with it, including putting it into proprietary closed source works, or putting it on github under another license.   But I am not a lawyer, and this is not legal advice, consult a lawyer if you want such advice.

**Comment by smcameron** [comment]
Also, thanks for asking (it wasn't necessary to ask at all, but it is very considerate, so thanks.)
